perspective_view:
  fname_img: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/data/perspective_views/DJI_0035.JPG'
  fname_val_pts: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0035_blue.txt'
  fname_ref_pts: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0035_white.txt'
  fname_fov_pts: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0035_fov_pts.txt'
  fname_K: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/data/calibration/mini3.json'
  angle: -43.0
  altitude: 10.4
top_view:
  fname_img: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/data/top_view/DJI_0017.JPG'
  fname_val_pts: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0017_blue.txt'
  fname_ref_pts: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0017_white.txt'
  scaling_factor: 54.67
selection:
  ref_pts: ['w19', 'w21', 'w25', 'w20', 'w18', 'w7', 'w5', 'w4', 'w6', 'w3', 'w1', 'w2', 'w15', 'w13', 'w14', 'w17']
  val_pts: ['b28', 'b27', 'b20', 'b18', 'b21', 'b19', 'b7', 'b6', 'b5', 'b3', 'b4', 'b13', 'b11', 'b12', 'b14', 'b15', 'b16', 'b17']
output:
  dir: 'out/DJI_0035.JPG'
