perspective_view:
  fname_img: '/Users/tobias/ziegleto/data/5Safe/vup/homography_evaluation/data/perspective_views/DJI_0049.JPG'
  fname_val_pts: '/Users/tobias/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0049_blue.txt'
  fname_ref_pts: '/Users/tobias/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0049_white.txt'
  fname_fov_pts: '/Users/tobias/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0049_fov_pts.txt'
  fname_K: '/Users/tobias/ziegleto/data/5Safe/vup/homography_evaluation/data/calibration/mini3.json'
  angle: -38.5
  altitude: 10.3
top_view:
  fname_img: '/Users/tobias/ziegleto/data/5Safe/vup/homography_evaluation/data/top_view/DJI_0017.JPG'
  fname_val_pts: '/Users/tobias/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0017_blue.txt'
  fname_ref_pts: '/Users/tobias/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0017_white.txt'
  scaling_factor: 54.67
selection:
  ref_pts: ['w11', 'w12', 'w13', 'w14', 'w15', 'w16', 'w18', 'w20', 'w5', 'w6', 'w7', 'w3', 'w22', 'w23', 'w24']
  val_pts: ['b12', 'b13', 'b14', 'b15', 'b16', 'b17', 'b18', 'b19', 'b20', 'b21', 'b22', 'b23', 'b24', 'b4', 'b5', 'b6', 'b8', 'b9']
output:
  dir: 'out/DJI_0049.JPG'
