perspective_view:
  fname_img: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/data/perspective_views/DJI_0061.JPG'
  fname_val_pts: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0061_blue.txt'
  fname_ref_pts: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0061_white.txt'
  fname_fov_pts: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0061_fov_pts.txt'
  fname_K: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/data/calibration/mini3.json'
  angle: -43.5
  altitude: 10.1
top_view:
  fname_img: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/data/top_view/DJI_0017.JPG'
  fname_val_pts: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0017_blue.txt'
  fname_ref_pts: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0017_white.txt'
  scaling_factor: 54.67
selection:
  ref_pts: ['w2', 'w5', 'w8', 'w13', 'w14', 'w15', 'w16', 'w17', 'w19', 'w25', 'w26']
  val_pts: ['b3', 'b4', 'b13', 'b14', 'b15', 'b16', 'b17', 'b27', 'b28', 'b29']
output:
  dir: 'out/DJI_0061.JPG'
