perspective_view:
  fname_img: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/data/perspective_views/DJI_0078.JPG'
  fname_val_pts: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0078_blue.txt'
  fname_ref_pts: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0078_white.txt'
  fname_fov_pts: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0078_fov_pts.txt'
  fname_K: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/data/calibration/mini3.json'
  angle: -36.8
  altitude: 10.3
top_view:
  fname_img: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/data/top_view/DJI_0017.JPG'
  fname_val_pts: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0017_blue.txt'
  fname_ref_pts: '/home/ziegleto/ziegleto/data/5Safe/vup/homography_evaluation/annotations/DJI_0017_white.txt'
  scaling_factor: 54.67
selection:
  ref_pts: ['w2', 'w4', 'w5', 'w6', 'w7', 'w10', 'w11', 'w12', 'w13', 'w14', 'w16', 'w17', 'w18', 'w19', 'w20', 'w21', 'w25']
  val_pts: ['b4', 'b6', 'b10', 'b11', 'b12', 'b13', 'b14', 'b15', 'b16', 'b17', 'b18', 'b19', 'b20', 'b21', 'b22', 'b27', 'b28', 'b29']
output:
  dir: 'out/DJI_0078.JPG'
